name = "CInterop"
uuid = "a4ecbb5e-2acf-4e9a-9bc0-297680d944ce"
authors = ["Nuzhdin Yury <nuzhin.urii@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
